backend:
  name: git-gateway
  branch: main

media_folder: static/images/uploads
public_folder: /images/uploads

collections:
    - name: posts
    label: المقالات
    folder: content/posts
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: العنوان, name: title, widget: string}
            - {label: تاريخ النشر, name: date, widget: datetime}
            - {label: صورة المقال, name: thumbnail, widget: image, required: false}
            - {label: الوصف المختصر, name: description, widget: text, required: false}
            - {label: محتوى المقال, name: body, widget: markdown}
