backend:
  name: git-gateway
  branch: main
  identity_url: https://almaydan-aljanubi.netlify.app/.netlify/identity
  gateway_url: https://almaydan-aljanubi.netlify.app/.netlify/git/github

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
    - name: "news"
    label: "الأخبار"
    folder: "_posts/news"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
            - {label: "العنوان", name: "title", widget: "string"}
            - {label: "التاريخ", name: "date", widget: "datetime"}
            - {label: "المحتوى", name: "body", widget: "markdown"}
